In [63]:
import numpy as np

In [72]:
#load IMS data (file should not include non-numbers, add first row to be the hours, i.e. 6,7,8...)
rdata = np.genfromtxt('/Users/alonhrl/Documents/Alon/MA-MSC/development/ims-data/9-21-4-22-months-data/ims-03-22.csv', delimiter=',',  missing_values=0)
rdata = rdata.astype('int32')

#clear any noise
with np.nditer(rdata, op_flags=['readwrite']) as it:
    for x in it:
        if x<0 or x>10000:
            print(x)
            x[...] = 0

print(rdata)

-2147483648
-2147483648
-2147483648
[[  0   7   8   9  10  11  12  13  14  15  16  17  18  19]
 [  0  40 193 391 535 687 753 765 673 537 243 120  11   0]
 [  0  28 153 341 491 721 728 683 456 304 190  75   8   0]
 [  0  17  95 345 295 313 261 440 433 378 127  89  19   0]
 [  0  22 217 401 569 751 798 721 710 528 483 155  16   0]
 [  0  48 216 430 620 746 801 796 719 580 390 176  21   0]
 [  0  33 100 371 450 526 559 658 501 378 271 145  19   0]
 [  0  31 202 445 473 688 798 819 699 465 288 142  22   0]
 [  0  40 175 324 439 615 559 473 469 472 380 184  15   0]
 [  0  15 121 218 479 566 544 695 706 437 225  86   9   0]
 [  1  81 124 228 652 721 836 781 795 421 229 100  29   0]
 [  0  19  82 156 219 319 374 674 635 408 182  66  13   0]
 [  0  32 114 173 141 196 247 278 715 349  76  36  14   0]
 [  1  86 321 525 729 255 470 297 265 196 149 119  28   0]
 [  0  26 124 231 418 718 905 581 740 651 313  95  16   0]
 [  0  67  69 382 353 819 570 684 662 669 443 249  47   0]
 [  1  73 318 543 73

##### Remove upper row which are the hours

In [ ]:
rdata = rdata[1:]
print(rdata)

##### Calculate accumulated radiation per day

In [ ]:
dsum = rdata.sum(axis=1)
print (dsum)

In [ ]:
# Add the days row
row, col = rdata.shape
days = np.empty(row, dtype=object)
for x in range(row):
    days[x] = x+1

In [ ]:
daySum = np.vstack([days, dsum])
print (daySum)

##### Add Eumetsat daily radiation

In [ ]:
eumetrdata = np.genfromtxt('/Users/alonhrl/Documents/Alon/MA-MSC/development/Eumetsat data/9-21-4-22-months-data/eumetsat-process-to-csv/mon_eumetsat_rad-03-22.csv', delimiter=',', dtype=np.int16)
eumetrdata = eumetrdata.astype('int16')

# calculate daily radiation
eumdsum = eumetrdata.sum(axis=1)
print (eumdsum)

In [ ]:
import matplotlib.pyplot as plt

x = daySum[0]
ims_daily = daySum[1]
eumetsat_daily = eumdsum

fig, ax = plt.subplots()

x = daySum[0]
ax.plot(x, eumetsat_daily, "-b" ,label="eumetsat_daily")
ax.plot(x, ims_daily, "-r", label="ims_daily")
ax.set_xticks(np.arange(0, len(x)+1, 1))
ax.set_xlabel('days', fontsize=14)
ax.set_ylabel('rad', fontsize=14)

fig.suptitle('Daily radiation', fontsize=14)
plt.rc('legend', fontsize=14)
plt.legend(loc="upper left")
plt.rcParams["figure.figsize"] = (20,8)
plt.rcParams.update({'font.size': 12})
##plt.rc('xtick', labelsize=8)
plt.draw()